
version: "3"

services:
  mongodb:
    image: docker.io/mongo:6.0
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD}
    volumes:
      - ./data:/data/db
    ports:
      - "27027:27017"

