
version: "3"


networks:
  appnet:

services:
  mongo1:
    image: docker.io/mongo:6.0
    #command: --replSet rs0
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=cuKpVrfZzUvg
    volumes:
      - ./mongo1-data:/data
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - appnet
    ports:
      - "28017:27017"

