version: "3"

services:
  nginx:
    image: docker.io/nginx:1.25-alpine
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./log:/var/log/nginx"
    ports:
      - "8080:80"

