
version: "3"

services:
  etcd1:
      image: docker.io/mysql:8.1
      restart: always
      volumes:
        - ./mysql-data/data:/var/lib/mysql
        - ./my.ini:/etc/mysql/conf.d/my.conf
      environment:
        - TZ=Asia/Shanghai
        - MYSQL_ROOT_PASSWORD=cuKpVrfZzUvg
        - MYSQL_DATABASE=test
      ports:
          - "3306:3306"
